version: v1.0.0
random_seed: 100

data_root: data
train_dataset: can
test_datasets: [can]

epoch: 200
batch_size: 8

print_freq_step: 10 
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [12,18,24]

anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25


prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results

prompts:
  normal: [
    flawless can surface,
    intact soda can,
    smooth metallic finish,
    consistent label printing,
    no scratches or defects,
    uniform cylindrical shape,
    perfect print alignment,
    clean and reflective surface,
    undamaged can texture,
    well-printed soda can
  ]

  abnormal: [
    print defect on can,
    label misprint,
    surface scratch on can,
    dented soda can,
    distorted logo or text,
    color misalignment,
    visible scratch mark,
    broken or damaged surface,
    irregular printing pattern,
    surface imperfection on metal
  ]
