version: v1.0.0
random_seed: 100

data_root: data
train_dataset: rice
test_datasets: [rice]

epoch: 200
batch_size: 8

print_freq_step: 10 
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [12,18,24]

anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25


prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results

prompts:
  normal: [
    clean rice grains,
    flawless white rice,
    pure rice batch,
    uniform rice texture,
    no foreign objects,
    well-sorted rice,
    consistent rice appearance,
    uncontaminated rice,
    high-quality rice grains,
    defect-free bulk rice
  ]

  abnormal: [
    foreign object in rice,
    plastic contamination in rice,
    visible impurity in rice,
    semi-transparent contaminant,
    dirty or mixed rice,
    rice with unusual texture,
    non-uniform rice batch,
    contaminated rice surface,
    rice with foreign particle,
    low-contrast defect in rice
  ]

