version: v1.0.0
random_seed: 100

data_root: data
train_dataset: vial
test_datasets: [vial]

epoch: 200
batch_size: 8

print_freq_step: 10 
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [12,18,24]

anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25


prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results

prompts:
  normal: [
    flawless vial,
    clean transparent vial,
    properly sealed vial,
    clear liquid with no particles,
    intact QR code on vial,
    correct fill level,
    uniform vial appearance,
    well-labeled and closed vial,
    defect-free medical vial,
    properly filled and sealed container
  ]

  abnormal: [
    foreign object in vial,
    missing or damaged QR code,
    incorrect fill level,
    open or missing vial cap,
    visible contamination in vial,
    partially filled vial,
    broken or distorted QR label,
    floating particle in liquid,
    low-contrast defect in transparent vial,
    improperly sealed medical container
  ]


