version: v1.0.0
random_seed: 100

data_root: data
train_dataset: walnuts
test_datasets: [walnuts]

epoch: 200
batch_size: 8

print_freq_step: 10 
val_freq_epoch: 1

image_size: 224
model_name: ViT-L-14
layers_out: [12,18,24]

anomaly_tasks:
  CutpasteTask: 0.25
  GaussIntensityChangeTask: 0.25
  SourceTask: 0.25
  IdentityTask: 0.25


prompt_maker: coop
n_learnable_token: 8
CSC: True
class_token_positions: [end]

save_root: results

prompts:
  normal: [
    intact walnut,
    whole and unbroken walnut,
    clean and complete shell,
    consistent walnut shape,
    no visible defects,
    undamaged walnut surface,
    well-formed walnut shell,
    defect-free batch of walnuts,
    uniform and natural walnut appearance,
    properly shaped and full walnuts
  ]

  abnormal: [
    cracked walnut shell,
    hole in walnut,
    broken or incomplete walnut,
    foreign object among walnuts,
    walnut with missing parts,
    damaged or split walnut,
    irregular or deformed walnut,
    visible contamination in walnut batch,
    overlapping or cut-off defective walnuts,
    walnut with structural imperfection
  ]




